### ISSUE TITLE
Options doesn't belong in user

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#11]
Now that the user has responsibility as a data object of handling credentials, seems more obvious that useroptions doesnt belong in user.

Perhaps Conceptually, user "has" options... But again, this breaks SRP.
As it is right now, The user class is used to:
1. Hold creds and details
2. Hold available / possible actions.
This is not ideal.
Why does user need to know their options? 

Going back to the real world, does user really "have" options? Or are options presented to them by virtue of limitation of possible actions depending on context?
If I am a user and I go to a library, does the librarian ask me what I can do? Or are my options (possible actions) are now limited because I am in a library?

Another reason for the issue is reduced flexibility, user options in the user class only makes sense in the bibliotica context, that limitation couples the idea of a user with the idea of it being in bibliotica.
Taking the user out of biblioteca, the optins no longer makes sense.

**Comment by Mochamoo** [comment]
Right. So it makes more sense for the user to query the library regarding their options than vice versa. I'll think of a way to shift that responsibility.

**Comment by Mochamoo** [comment]
I've given options to the LibraryManagementSystem instead of User.
