### ISSUE TITLE
Library management system #checkout and #return should not return user message

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#12]
The responsibility of the checkout method is  checkout the book.
By returning the string it breaks SRP because now it does multiple things
1. manages the book inventory
2. Telling the user a message of what happened.

This makes the code less flexible. 
Because if you want "failed checkout" to do the followingt:
- checks another library and give new location
- respond in different language depending on user interface
- suggest a different book.
Then the string no longer makes sense.

This is similar with the method of returning the book

**Comment by lfendy** [comment]
Returning boolean is fine

**Comment by Mochamoo** [comment]
Okay. By returning a String to denote failure, I could be misleading the user in future cases where something else causes the checkout to fail. And also by returning a String to denote failure I'm adding more responsibility to the method which breaks SRP. I'll make sure to change that.

**Comment by lfendy** [comment]
The examples I gave was more around what to do with the failure, where
giving the user the message is only ONE of many possibilities.
You can do more things when checkout fail, and by returning a string, you
have effectively killed all other possibilities

**Comment by Mochamoo** [comment]
Checkout and return within the LibraryManagementSystem now return boolean. I've left it up to the Menu to interpret the boolean and display success/failure messages accordingly.
