### ISSUE TITLE
The messages should not contain \n

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#13]
This is coupling the content of the message and the presentation of the message.

The \n will no longer make sense if you'd like to present the message to render in separate window, or an alert box or a div in html.

**Comment by Mochamoo** [comment]
\n has been removed from the return value. Cheers.

**Comment by lfendy** [comment]
There are still \n in many place in code. 

I'm debating myself whether the complexity of returning array of strings and just perform loop of println is worth the removal of \n everywhere.

Maybe... Maybe not.. i'll leave it to you.

Another thing I've seen people do in Java is to assign a NewLine Constant which is environment/platform specific.

http://stackoverflow.com/questions/207947/how-do-i-get-a-platform-dependent-new-line-character

**Comment by Mochamoo** [comment]
I suppose I hadn't considered the effects of \n in that much depth. I thought returning \n was the only issue, and didn't know that they were also undesirable in println.

I'm interested in using the first option (looping through array), but am wondering if readability is a concern here. What would you do, Fendy?

I suppose it wouldn't be too bad if the code was formatted to be readable while adding to the array, then just loop through as normal.

**Comment by lfendy** [comment]
Going back to trying to decouple message content and presentation. Looping through an array is definitely more future proof.

If not, its still worth considering changing \n with platform independent newline

**Comment by Mochamoo** [comment]
I ended up using both methods. I removed newlines from BookList display, MovieList display and User display methods. They now return an ArrayList of String, and the menu has method to loop through and display the contents.
