### ISSUE TITLE
LoginHandler breaks SRP

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#14]
LoginHandler currently hashes password and asks for user input.
You should not get user input from within Login Handler.
Similarly, you should not print out from Login Handler.

If you are using stdin and stdout, make it a habit to keep all your stdin/stdout manipulation in one place. And its usually in the UI or main method, etc.

In your case it looks like the Menu.

The reason is to isolate the interactive part of your code, with the business logic part of your code.
The interactive part of your code can further be split out to "view" and "service" if needed. But the basic idea is that the businesslogic (like login / password validation) only need to care about the logic, not about telling user what to do and expecting things from the user. 

Additionally, if the program change to no longer use stdin/stdout, the business logic can stay the same.

**Comment by Mochamoo** [comment]
I've moved the prompts from LoginHandler to Menu.
