### ISSUE TITLE
MenuOptionsInput#getOption can be rewritten to state intent

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#15]
Instead of 

While(input == null || input == "xxxxxx")
{
validateAgainstOption
}

You can write it as "while isInvalid(input)"

**Comment by Mochamoo** [comment]
I've dropped the getOption method from the MenuOptionsInput (now MenuOptionsService) class and given a variant of it to the Menu class, as that's where the prompt for input should come from. Menu now has a method getOptionFromUser. This new method in Menu calls the validateAgainstOptions from MenuOptionsService to perform validation.

**Comment by lfendy** [comment]
Reopen as Issue #26
