### ISSUE TITLE
Biblioteca app, separate setup / init activities into its own setup method

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#18]
Libsystem.adduser and .addbooks

Also .addbooks doesnot need to live under successful login

**Comment by Mochamoo** [comment]
I was debating about this one. My reasoning was that I didn't want to create a bunch of books before the user can interact with them. Your thoughts?

**Comment by lfendy** [comment]
Conceptually, the library exists (with books) irrespective of the user
being able to log in.

On 24 Feb. 2017 9:34 pm, "Eugene Tang" <notifications@github.com> wrote:

I was debating about this one. My reasoning was that I didn't want to
create a bunch of books before the user can interact with them. Your
thoughts?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mochamoo/twu-biblioteca-eugene/issues/18#issuecomment-282259593>,
or mute the thread

**Comment by Mochamoo** [comment]
Nice. Cheers.

**Comment by lfendy** [comment]
It also decouples "setup/initialisation" with "login"

**Comment by Mochamoo** [comment]
I've put an initialiseDatabase method into LibraryManagementSystem that performs all this loading, and moved it out of main.

**Comment by lfendy** [comment]
Keeping it in bibliotecaApp is ok, just separate the method
