### ISSUE TITLE
Don't use inheritance, mixing software/programming context with domain context

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#19]
Inheritance is used to denote subcategory.

Programming context:
ArrayList is a List
HashMap is a Map

Domain:
Car is a Vehicle
FictionBook is a Book

What you should NOT do, is create inheritance that mixes them.
Don't do CarList inherits List.

In your case BookList Has an arrayList, not is an arraylist..
So that example is fine.

What you have in the code is menuOptionsInput and userInput.
In both cases, they are inheriting a software concept but for a domain model.
It might be better to not have then inherit "input", but instead create a menuOptionsService and userService

**Comment by lfendy** [comment]
Refer to:
How to Misuse Inheritance - Example 2
https://www.thoughtworks.com/insights/blog/composition-vs-inheritance-how-choose

**Comment by Mochamoo** [comment]
That's one I was really iffy about while I working. Their role seems to be more on the formatting/validating side rather than getting input.

**Comment by Mochamoo** [comment]
The two classes no longer inherit from Input.
