### ISSUE TITLE
Conceptually, having book authors make more sense than book author names

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#20]
Instead of having authornamelist, keep it as authorlist, introduce back the author class, where author has a name

**Comment by lfendy** [comment]
This allows flexibility in the future when more author metadata is required.
I.e. author genre, number of book published, pen names, years active, etc...

**Comment by Mochamoo** [comment]
Author has been restored. Additionally, I've added a Director class for movies.
