### ISSUE TITLE
Input lives in view.

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#21]
Input is presentation layer. Not service layer

**Comment by Mochamoo** [comment]
I was thinking that view is reserved for classes that emphasise displaying things to the user, so I'm quite surprised about this one. Is it because Input interacts directly with the user that it goes into view?

**Comment by lfendy** [comment]
View usually represents the presentation layer. Yes, it usually encompass
user input.

On 25 Feb. 2017 10:52 am, "Eugene Tang" <notifications@github.com> wrote:

I was thinking that view is reserved for classes that emphasise displaying
things to the user, so I'm quite surprised about this one. Is it because
Input interacts directly with the user that it goes into view?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mochamoo/twu-biblioteca-eugene/issues/21#issuecomment-282436931>,
or mute the thread

**Comment by Mochamoo** [comment]
All classes are in their appropriate package now, I believe. Those whose primary purpose is to hold data and "model" things are in the Model package, and classes that manipulate the data of those classes have been put into Service.
