### ISSUE TITLE
Manager lives in service

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#22]
And maybe rename them to service

**Comment by Mochamoo** [comment]
I'm using this as a rough guide.
http://stackoverflow.com/questions/5702391/mvcs-model-view-controller-service

Before then, I thought service was more for utility-like classes. Didn't realise business logic sat in there. I'll rename the Management/Manager classes to Service and put them in there.

**Comment by lfendy** [comment]
Depends which camp you sit. In ruby-land, there are rarely any service. And
business logic lives in model. But in ruby-land, it's also common to not
have DAO (data access object) and ORM (object relational mapping) as
separate from model.
