### ISSUE TITLE
Maybe rename Handler to service

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#23]
Login Handler

**Comment by Mochamoo** [comment]
I've renamed the classes. This should address issue #25 as well.

**Comment by lfendy** [comment]
Still not renamed

**Comment by Mochamoo** [comment]
Embarrassingly strange. Thought I had. I'll get to it.

**Comment by Mochamoo** [comment]
Okay. Done.
