### ISSUE TITLE
Cryptic while condition in menu

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#26]
while((input = optionsFormatter.validateAgainstOptions(input)) == null) 

Sorry Eugene, it's difficult to read and to understand the intent. 
Also, Please don't make assignment and comparison in the same line.

**Comment by Mochamoo** [comment]
The validateAgainstOptions method was breaking SRP. I was using it to validate and at the same time return a valid String. I've since changed it to only output true/false, and let another method output the valid String.

**Comment by lfendy** [comment]
while((username = usernameFormatter.getFormattedUsername(username)) == null) {

**Comment by Mochamoo** [comment]
Done the same thing with UsernameService.
