### ISSUE TITLE
BookList#populateBookList does not belong there.

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#5]
Ever heard about magic numbers in code and why they are bad? Your populateBookList is hardcoding its own value into the model. This is usually not recommended.
It's NOT the responsibility of the Booklist to populate itself.

If you want to reuse booklist in different context (containing different books) then populateBookList makes absolutely no sense.

**Comment by Mochamoo** [comment]
Thanks. I'll change the method to load up the books from a text file.

**Comment by lfendy** [comment]
Not necessarily.
It's not the responsibility of the booklist to populate itself.

So changing the method inside the booklist is still not ideal, even if it
reads from a text file.

You can hardcode your books, but do so in the main or the setup methods.
And have the main or setup method call "add books" to the booklist

**Comment by Mochamoo** [comment]
Right. So the issue was that I was blurring the role of the Booklist. I've begun taking that responsibility away from Booklist; I've instead given it to the LibraryManagementSystem.
