### ISSUE TITLE
LibraryManagementSystem needs to be redesigned.

### ISSUE THREAD

**Issue by lfendy** [Mochamoo/twu-biblioteca-eugene#7]
Issues:
Most of the methods breaks SRP (Single Responsibility Principle)

Method inside LibraryManagementSystem that uses input and print out menu and check whether or not things are valid feels really awkward.

**Comment by Mochamoo** [comment]
Cheers, Fendy. Could you go into this one in a little more detail? Perhaps bring up an example of what you didn't like and then state what you expected?

**Comment by lfendy** [comment]
E.g.
The message given out to the user does not belong inside LibraryManagementSystem
(The lib management system class is reponsible for knowing whether or not u can borrow, and managing list of books)

Input (getuserinput) also does not belong there.
It should receive a string from outside the library, not create its own scanner

**Comment by lfendy** [comment]
Generating header and booklists can stay

**Comment by Mochamoo** [comment]
That's cool. Thanks. Ideally, where should Input be created? Right now I'm thinking of handling book selection in the menu. Get the input there then pass it as String to the relevant methods in LibraryManagementSystem.

**Comment by lfendy** [comment]
Sure. The menu then conceptually can become the user's UI. Messages to the user, (like thank you, success, fail and question prompts can also live near there)

**Comment by Mochamoo** [comment]
I've taken the responsibility from LibraryManagementSystem and given it to Menu.
